services:

  web:
    build:
      context: ./apps/web

    container_name: v5r-web

    ports:
      - "5173:5173"

    restart: unless-stopped

  api:
    build:
      context: ./apps/api

    container_name: v5r-api

    environment:
      PORT: 3000

    ports:
      - "3000:3000"

    restart: unless-stopped
