import { useState } from 'react'
import './chronicle-entity-image.css'
type AssetType = 'NPC' | 'LOCATION' | 'RESOURCE'
export function ChronicleEntityImage({ chronicleId, assetType, assetId, label }: { chronicleId: string; assetType: AssetType; assetId: string; label: string }) {
  const [revision, setRevision] = useState(0); const [available, setAvailable] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const url = '/api/chronicles/' + chronicleId + '/assets/' + assetType + '/' + assetId + '/image?v=' + revision
  async function upload(file: File | null) { if (!file) return; if (!['image/jpeg','image/png','image/webp'].includes(file.type) || file.size > 2 * 1024 * 1024) { setError('Usa JPG, PNG o WEBP de hasta 2 MB.'); return } setBusy(true); setError(''); try { const response = await fetch(url, { method: 'PUT', credentials: 'include', headers: { 'Content-Type': file.type }, body: await file.arrayBuffer() }); if (!response.ok) throw new Error(); setAvailable(true); setRevision(Date.now()) } catch { setError('No se pudo guardar la imagen.') } finally { setBusy(false) } }
  async function remove() { setBusy(true); setError(''); try { const response = await fetch(url, { method: 'DELETE', credentials: 'include' }); if (!response.ok) throw new Error(); setAvailable(false); setRevision(Date.now()) } catch { setError('No se pudo eliminar la imagen.') } finally { setBusy(false) } }
  return <section className="chronicle-entity-image" aria-label={'Imagen de ' + label}><div className="chronicle-entity-image__preview">{available ? <img src={url} alt={'Imagen de ' + label} onError={() => setAvailable(false)} /> : <span aria-hidden="true">◇</span>}</div><div><h4>Imagen del recurso</h4><p>{available ? 'Se reutiliza automáticamente en el Cuaderno.' : 'Sin imagen asignada.'}</p><label className="chronicle-entity-image__upload"><span>{busy ? 'Guardando…' : 'Subir o reemplazar'}</span><input disabled={busy} type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => void upload(event.currentTarget.files?.[0] ?? null)} /></label>{available && <button type="button" disabled={busy} onClick={() => void remove()}>Quitar imagen</button>}{error && <small role="alert">{error}</small>}</div></section>
}
