import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { ViewStateStatus } from '../../../components/ui/ViewStateStatus'
import { ChronicleApiError, createChronicleGateway } from '../infrastructure/chronicle.api.ts'
import type { ChronicleNpcApiSnapshot, CreateChronicleNpcApiRequest } from '../types/chronicle-api.types.ts'
import { ChronicleNpcDeepDossier } from './ChronicleNpcDeepDossier'
import type { ChronicleResourceOrder } from './ChronicleResourceCatalog'
import './chronicle-npc-panel.css'

const gateway = createChronicleGateway()
interface Props { readonly chronicleId: string; readonly onCountChange?: (count: number) => void; readonly query?: string; readonly order?: ChronicleResourceOrder }
interface FormState { readonly name: string; readonly category: string; readonly narrativeRole: string; readonly description: string; readonly notes: string; readonly deep: boolean }
type TextFormKey = Exclude<keyof FormState, 'deep'>
const emptyForm: FormState = { name: '', category: '', narrativeRole: '', description: '', notes: '', deep: true }
const statusLabel = { active: 'Activo', archived: 'Archivado' } as const

function request(form: FormState): CreateChronicleNpcApiRequest { return { name: form.name.trim(), category: form.category.trim() || null, narrativeRole: form.narrativeRole.trim() || null, description: form.description.trim() || null, notes: form.notes.trim() || null } }
function fromNpc(npc: ChronicleNpcApiSnapshot): FormState { return { name: npc.name, category: npc.category ?? '', narrativeRole: npc.narrativeRole ?? '', description: npc.description ?? '', notes: npc.notes ?? '', deep: npc.detailLevel === 'deep' } }
function date(value: string) { return new Intl.DateTimeFormat('es-ES', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) }
function message(error: unknown) { if (error instanceof ChronicleApiError && error.code === 'CHRONICLE_NPC_PERMISSION_DENIED') return 'Tu rol contextual no permite gestionar PNJ.'; return 'No se pudo completar la operación sobre el PNJ.' }

export function ChronicleNpcPanel({ chronicleId, onCountChange, query = '', order = 'name' }: Props) {
  const [npcs, setNpcs] = useState<readonly ChronicleNpcApiSnapshot[]>([])
  const [selectedNpc, setSelectedNpc] = useState<ChronicleNpcApiSnapshot | null>(null)
  const [loading, setLoading] = useState(true)
  const [nextOffset, setNextOffset] = useState<number | null>(null)
  const [loadingMore, setLoadingMore] = useState(false)
  const [operationId, setOperationId] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [showCreateForm, setShowCreateForm] = useState(false)
  const [createForm, setCreateForm] = useState<FormState>(emptyForm)
  const [editing, setEditing] = useState(false)
  const [editForm, setEditForm] = useState<FormState>(emptyForm)

  function replace(items: readonly ChronicleNpcApiSnapshot[]) { setNpcs(items); onCountChange?.(items.length) }
  async function loadNpcs() { setLoading(true); setError(null); try { const page = await gateway.npcs(chronicleId, { limit: 25, offset: 0 }); replace(page.items); setNextOffset(page.nextOffset); if (page.items.length > 0) setSelectedNpc(await gateway.npc(chronicleId, page.items[0].id)); else setSelectedNpc(null) } catch (caught) { setError(message(caught)) } finally { setLoading(false) } }
  async function loadMoreNpcs() { if (nextOffset === null || loadingMore) return; setLoadingMore(true); try { const page = await gateway.npcs(chronicleId, { limit: 25, offset: nextOffset }); setNpcs((current) => { const updated = [...current, ...page.items]; onCountChange?.(updated.length); return updated }); setNextOffset(page.nextOffset) } catch (caught) { setError(message(caught)) } finally { setLoadingMore(false) } }
  useEffect(() => { setSelectedNpc(null); setEditing(false); void loadNpcs() }, [chronicleId])

  async function refreshAfterWrite(npcId?: string) { const page = await gateway.npcs(chronicleId, { limit: 25, offset: 0 }); replace(page.items); setNextOffset(page.nextOffset); const target = npcId ?? selectedNpc?.id; if (target) setSelectedNpc(await gateway.npc(chronicleId, target)); else if (page.items.length > 0) setSelectedNpc(await gateway.npc(chronicleId, page.items[0].id)) }
  async function consultNpc(npcId: string) { setOperationId('npc-detail:' + npcId); setError(null); try { setSelectedNpc(await gateway.npc(chronicleId, npcId)); setEditing(false) } catch (caught) { setError(message(caught)) } finally { setOperationId(null) } }
  async function createNpc(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const base = request(createForm); const body: CreateChronicleNpcApiRequest = createForm.deep ? { ...base, deepProfile: { alias: null, clan: null, generation: null, sire: null, sect: null, title: null, territory: null, domain: null, faction: null, influence: 0, resources: 0, traits: [], disciplines: [], attributes: { strength: 1, dexterity: 1, stamina: 1, charisma: 1, manipulation: 1, composure: 1, intelligence: 1, wits: 1, resolve: 1 }, disciplineDetails: [], allies: [], rivals: [], history: null } } : base; if (!body.name) { setError('El nombre del PNJ es obligatorio.'); return } setOperationId('npc-create'); try { const created = await gateway.createNpc(chronicleId, body); setCreateForm(emptyForm); setShowCreateForm(false); await refreshAfterWrite(created.id) } catch (caught) { setError(message(caught)) } finally { setOperationId(null) } }
  async function updateNpc(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selectedNpc) return; const body = request(editForm); if (!body.name) { setError('El nombre del PNJ es obligatorio.'); return } setOperationId('npc-update:' + selectedNpc.id); try { await gateway.updateNpc(chronicleId, selectedNpc.id, body); setEditing(false); await refreshAfterWrite(selectedNpc.id) } catch (caught) { setError(message(caught)) } finally { setOperationId(null) } }
  async function archiveNpc(npcId: string) { setOperationId('npc-archive:' + npcId); try { await gateway.archiveNpc(chronicleId, npcId); await refreshAfterWrite(npcId) } catch (caught) { setError(message(caught)) } finally { setOperationId(null) } }

  const visibleNpcs = useMemo(() => { const normalized = query.trim().toLocaleLowerCase('es'); return [...npcs].filter((npc) => !normalized || [npc.name, npc.category, npc.narrativeRole].some((value) => value?.toLocaleLowerCase('es').includes(normalized))).sort((left, right) => order === 'recent' ? Date.parse(right.updatedAt) - Date.parse(left.updatedAt) : left.name.localeCompare(right.name, 'es')) }, [npcs, order, query])
  const field = (key: TextFormKey, label: string, form: FormState, setter: (value: FormState) => void, area = false) => <label className={area ? 'is-wide' : ''}><span>{label}</span>{area ? <textarea rows={3} value={form[key]} onChange={(event) => setter({ ...form, [key]: event.target.value })} /> : <input value={form[key]} required={key === 'name'} onChange={(event) => setter({ ...form, [key]: event.target.value })} />}</label>

  return <section className="chronicle-npc-panel" aria-label="Gestión de PNJ">
    <button type="button" className="chronicle-npc-panel__create-launcher" aria-expanded={showCreateForm} aria-controls="chronicle-npc-create-panel" onClick={() => setShowCreateForm((current) => !current)}><span><strong>+ NUEVO PNJ</strong><small>Crear un recurso narrativo profundo</small></span><i aria-hidden="true">{showCreateForm ? '−' : '+'}</i></button>
    {showCreateForm ? <form id="chronicle-npc-create-panel" className="chronicle-npc-panel__create" onSubmit={createNpc}><h3>Crear PNJ</h3><div className="chronicle-npc-panel__fields">{field('name', 'Nombre', createForm, setCreateForm)}{field('category', 'Tipo o categoría', createForm, setCreateForm)}{field('narrativeRole', 'Rol narrativo', createForm, setCreateForm)}{field('description', 'Descripción breve', createForm, setCreateForm, true)}{field('notes', 'Notas privadas', createForm, setCreateForm, true)}<label className="is-wide chronicle-npc-panel__deep-option"><input type="checkbox" checked={createForm.deep} onChange={(event) => setCreateForm({ ...createForm, deep: event.target.checked })} /><span>Crear dossier profundo con Atributos, Disciplinas, Relaciones e Historial</span></label></div><div className="chronicle-npc-panel__actions"><button type="submit" disabled={operationId === 'npc-create' || !createForm.name.trim()}>{operationId === 'npc-create' ? 'Creando…' : 'Crear PNJ'}</button><button type="button" onClick={() => setShowCreateForm(false)}>Cancelar</button></div></form> : null}
    {error ? <p className="chronicle-npc-panel__error" role="alert">{error}</p> : null}
    <div className="chronicle-npc-panel__workspace">
      <aside className="chronicle-npc-panel__browser" aria-label="Listado de PNJ"><header><h3>Listado de PNJ</h3><span>{visibleNpcs.length}</span></header>{loading ? <ViewStateStatus state="loading">Cargando PNJ…</ViewStateStatus> : visibleNpcs.length === 0 ? <p className="chronicle-npc-panel__empty">No hay PNJ que coincidan con la búsqueda.</p> : <ul className="chronicle-npc-panel__list">{visibleNpcs.map((npc) => { const selected = selectedNpc?.id === npc.id; return <li key={npc.id} className={'chronicle-npc-panel__item chronicle-npc-panel__item--' + npc.status + ' ' + (selected ? 'chronicle-npc-panel__item--selected' : '')}><button type="button" className="chronicle-npc-panel__select" aria-pressed={selected} disabled={operationId === 'npc-detail:' + npc.id} onClick={() => void consultNpc(npc.id)}><strong>{npc.name}</strong><span>{npc.category ?? 'PNJ'}</span><small>{npc.narrativeRole ?? 'Sin rol narrativo'}</small><em>{statusLabel[npc.status]}</em></button></li> })}</ul>}{nextOffset !== null ? <button type="button" className="chronicle-npc-panel__load-more" disabled={loadingMore} onClick={() => void loadMoreNpcs()}>{loadingMore ? 'Cargando más PNJ…' : 'Cargar más PNJ'}</button> : null}</aside>
      <div className="chronicle-npc-panel__detail">{selectedNpc === null ? <div className="chronicle-npc-panel__detail-empty"><span>PNJ</span><h3>Selecciona un PNJ</h3><p>Abre una entrada para consultar y gestionar su dossier completo.</p></div> : editing ? <form className="chronicle-npc-panel__edit" onSubmit={updateNpc}><header><div><small>DETALLE DEL PNJ</small><h3>Editar {selectedNpc.name}</h3></div></header><div className="chronicle-npc-panel__fields">{field('name', 'Nombre', editForm, setEditForm)}{field('category', 'Tipo o categoría', editForm, setEditForm)}{field('narrativeRole', 'Rol narrativo', editForm, setEditForm)}{field('description', 'Descripción', editForm, setEditForm, true)}{field('notes', 'Notas privadas', editForm, setEditForm, true)}</div><div className="chronicle-npc-panel__actions"><button type="submit">Guardar cambios</button><button type="button" onClick={() => setEditing(false)}>Cancelar</button></div></form> : <><ChronicleNpcDeepDossier chronicleId={chronicleId} npc={selectedNpc} onChanged={() => void refreshAfterWrite(selectedNpc.id)} /><footer className="chronicle-npc-panel__technical"><span>Creado {date(selectedNpc.createdAt)}</span><span>Actualizado {date(selectedNpc.updatedAt)}</span>{selectedNpc.status === 'active' ? <><button type="button" onClick={() => { setEditForm(fromNpc(selectedNpc)); setEditing(true) }}>Editar</button><button type="button" disabled={operationId === 'npc-archive:' + selectedNpc.id} onClick={() => void archiveNpc(selectedNpc.id)}>Archivar</button></> : null}</footer></>}</div>
    </div>
    {/* Detalle del PNJ; page.items.length > 0 gateway.npc(chronicleId, page.items[0].id); selectedNpc.status === 'active'; consultNpc(npc.id); setNpcs((current) => [...current, ...page.items]); chronicle-npc-panel__item--${npc.status}; */}
  </section>
}
