import { FormEvent, useEffect, useState } from 'react'
import { createUserAdministrationGateway } from '../infrastructure/user-administration.api'
import type { AdministrationRole, AdministrationUser } from '../types/user-administration.types'
import './administration-hub.css'
const api=createUserAdministrationGateway(); const roles:readonly AdministrationRole[]=['admin','narrator','player']
export function AdministrationHub(){ const [users,setUsers]=useState<readonly AdministrationUser[]>([]); const [message,setMessage]=useState(''); const [loading,setLoading]=useState(true)
 const load=async()=>{setLoading(true);try{setUsers(await api.list())}catch{setMessage('No se pudieron cargar las cuentas.')}finally{setLoading(false)}}; useEffect(()=>{void load()},[])
 const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const selected=roles.filter(r=>f.get(r)==='on');try{await api.create({username:String(f.get('username')),displayName:String(f.get('displayName')),password:String(f.get('password')),roles:selected});e.currentTarget.reset();setMessage('Cuenta creada.');await load()}catch{setMessage('No se pudo crear la cuenta.')}}
 const status=async(user:AdministrationUser)=>{const next=user.status==='active'?'disabled':'active';if(!window.confirm(`Confirmar cambio de estado para ${user.username}?`))return;try{await api.changeStatus(user.id,next);await load()}catch{setMessage('No se pudo cambiar el estado.')}}
 const reset=async(user:AdministrationUser)=>{const password=window.prompt(`Nueva contraseña para ${user.username}`);if(!password)return;try{await api.resetPassword(user.id,password);setMessage('Contraseña restablecida.')}catch{setMessage('No se pudo restablecer la contraseña.')}}
 const toggleRole=async(user:AdministrationUser,role:AdministrationRole)=>{const next=user.roles.includes(role)?user.roles.filter(r=>r!==role):[...user.roles,role];if(!next.length){setMessage('Una cuenta debe conservar al menos un rol.');return}try{await api.changeRoles(user.id,next);await load()}catch{setMessage('No se pudieron actualizar los roles.')}}
 return <section className="administration-hub"><header className="administration-hub__header"><div><p className="eyebrow">ADMINISTRACIÓN</p><h1>Centro administrativo</h1><p>Gestiona cuentas y accesos del sistema.</p></div><button type="button" onClick={()=>void load()}>Actualizar</button></header>{message&&<p className="administration-hub__notice" role="status">{message}</p>}<div className="administration-hub__grid"><article className="administration-hub__card"><h2>Crear cuenta</h2><form onSubmit={create}><label>Usuario<input required name="username" autoComplete="username" /></label><label>Nombre visible<input required name="displayName" /></label><label>Contraseña inicial<input required minLength={8} name="password" type="password" autoComplete="new-password" /></label><div className="administration-hub__roles">{roles.map(role=><label key={role}><input name={role} type="checkbox" defaultChecked={role==='player'} />{role}</label>)}</div><button type="submit">Crear cuenta</button></form></article><article className="administration-hub__card"><h2>Usuarios y cuentas</h2>{loading?<p>Cargando cuentas…</p>:users.map(user=><div className="administration-hub__user" key={user.id}><div><strong>{user.displayName}</strong><br/><span>{user.username} · {user.status}</span><div className="administration-hub__roles">{roles.map(role=><label key={role}><input checked={user.roles.includes(role)} onChange={()=>void toggleRole(user,role)} type="checkbox" />{role}</label>)}</div></div><div className="administration-hub__actions"><button type="button" onClick={()=>void status(user)}>{user.status==='active'?'Desactivar':'Activar'}</button><button type="button" onClick={()=>void reset(user)}>Restablecer contraseña</button></div></div>)}</article></div><article className="administration-hub__card"><h2>Operaciones del sistema</h2><p>El mantenimiento, copias, recuperación, configuración técnica y registros se incorporarán en la siguiente fase administrativa.</p></article></section> }
