import { Inject, Injectable } from '@nestjs/common'
import { DatabaseService } from '../../database/database.service'
import { CHRONICLE_PARTICIPANT_REPOSITORY } from './chronicle-participant.repository'
import { assertChronicleEventNarrator } from './chronicle-event-permission'
import type { ChronicleParticipantRepository } from './chronicle-participant.repository'
export class ChronicleEventRelationsNotFoundError extends Error {}
export class ChronicleEventRelationsInvalidTargetError extends Error {}
export interface ChronicleEventRelations { readonly characterIds: readonly string[]; readonly npcIds: readonly string[]; readonly locationIds: readonly string[] }
@Injectable()
export class ManageChronicleEventRelationsUseCase {
  constructor(private readonly database: DatabaseService, @Inject(CHRONICLE_PARTICIPANT_REPOSITORY) private readonly participants: ChronicleParticipantRepository) {}
  private async event(actorUserId:string,chronicleId:string,eventId:string){await assertChronicleEventNarrator(this.participants,actorUserId,chronicleId);const event=await this.database.chronicleEvent.findFirst({where:{id:eventId,chronicleId},select:{id:true}});if(event===null)throw new ChronicleEventRelationsNotFoundError()}
  async load(actorUserId:string,chronicleId:string,eventId:string):Promise<ChronicleEventRelations>{await this.event(actorUserId,chronicleId,eventId);const [characters,npcs,locations]=await Promise.all([this.database.chronicleEventCharacter.findMany({where:{eventId},select:{characterId:true},orderBy:{characterId:'asc'}}),this.database.chronicleEventNpc.findMany({where:{eventId},select:{npcId:true},orderBy:{npcId:'asc'}}),this.database.chronicleEventLocation.findMany({where:{eventId},select:{locationId:true},orderBy:{locationId:'asc'}})]);return{characterIds:characters.map(value=>value.characterId),npcIds:npcs.map(value=>value.npcId),locationIds:locations.map(value=>value.locationId)}}
  async replace(actorUserId:string,chronicleId:string,eventId:string,input:ChronicleEventRelations):Promise<ChronicleEventRelations>{await this.event(actorUserId,chronicleId,eventId);const [characters,npcs,locations]=await Promise.all([this.database.character.findMany({where:{id:{in:[...input.characterIds]},chronicleId},select:{id:true}}),this.database.chronicleNpc.findMany({where:{id:{in:[...input.npcIds]},chronicleId},select:{id:true}}),this.database.chronicleLocation.findMany({where:{id:{in:[...input.locationIds]},chronicleId},select:{id:true}})]);if(characters.length!==input.characterIds.length||npcs.length!==input.npcIds.length||locations.length!==input.locationIds.length)throw new ChronicleEventRelationsInvalidTargetError();await this.database.$transaction(async transaction=>{await transaction.chronicleEventCharacter.deleteMany({where:{eventId}});await transaction.chronicleEventNpc.deleteMany({where:{eventId}});await transaction.chronicleEventLocation.deleteMany({where:{eventId}});if(input.characterIds.length>0)await transaction.chronicleEventCharacter.createMany({data:input.characterIds.map(characterId=>({eventId,characterId,chronicleId}))});if(input.npcIds.length>0)await transaction.chronicleEventNpc.createMany({data:input.npcIds.map(npcId=>({eventId,npcId,chronicleId}))});if(input.locationIds.length>0)await transaction.chronicleEventLocation.createMany({data:input.locationIds.map(locationId=>({eventId,locationId,chronicleId}))})});return input}
}
