import { BadRequestException, Body, Controller, ForbiddenException, Get, NotFoundException, Param, Patch, Req, UnauthorizedException } from '@nestjs/common'
import { ChronicleEventPermissionError } from '../application/chronicle-event-permission'
import { ChronicleEventRelationsInvalidTargetError, ChronicleEventRelationsNotFoundError, ManageChronicleEventRelationsUseCase } from '../application/manage-chronicle-event-relations.use-case'
import { parseChronicleIdParam, parseChronicleNarratorId } from './chronicle.dto'
import { parseChronicleEventIdParam } from './chronicle-event.dto'
interface RequestWithUser { readonly user?: { readonly id?: unknown } }
function ids(value:unknown,field:string):readonly string[]{const record=value as { readonly ids?: unknown };if(!record||typeof record!=='object'||!Array.isArray(record.ids))throw new BadRequestException({code:'INVALID_CHRONICLE_EVENT_RELATIONS_REQUEST',field});const values=record.ids;if(new Set(values).size!==values.length||values.some(id=>typeof id!=='string'||!/^[0-9a-f-]{36}$/i.test(id)))throw new BadRequestException({code:'INVALID_CHRONICLE_EVENT_RELATIONS_REQUEST',field});return values}
@Controller('chronicles/:chronicleId/events/:eventId/relations')
export class ChronicleEventRelationsController { constructor(private readonly relations:ManageChronicleEventRelationsUseCase){} private actor(request:RequestWithUser){try{return parseChronicleNarratorId(request.user?.id)}catch{throw new UnauthorizedException({code:'AUTHENTICATION_REQUIRED'})}} private event(c:unknown,e:unknown){return{chronicleId:parseChronicleIdParam(c),eventId:parseChronicleEventIdParam(e)}} private fail(error:unknown):never{if(error instanceof ChronicleEventPermissionError)throw new ForbiddenException({code:'CHRONICLE_EVENT_PERMISSION_DENIED'});if(error instanceof ChronicleEventRelationsNotFoundError)throw new NotFoundException({code:'CHRONICLE_EVENT_NOT_FOUND'});if(error instanceof ChronicleEventRelationsInvalidTargetError)throw new BadRequestException({code:'INVALID_CHRONICLE_EVENT_RELATION_TARGET'});throw error}
 @Get() async load(@Req() request:RequestWithUser,@Param('chronicleId') c:unknown,@Param('eventId') e:unknown){try{const id=this.event(c,e);return await this.relations.load(this.actor(request),id.chronicleId,id.eventId)}catch(error){this.fail(error)}}
 @Patch() async replace(@Req() request:RequestWithUser,@Param('chronicleId') c:unknown,@Param('eventId') e:unknown,@Body() body:unknown){try{const id=this.event(c,e);const data=body as { readonly characterIds?: unknown; readonly npcIds?: unknown; readonly locationIds?: unknown };return await this.relations.replace(this.actor(request),id.chronicleId,id.eventId,{characterIds:ids({ids:data?.characterIds},'characterIds'),npcIds:ids({ids:data?.npcIds},'npcIds'),locationIds:ids({ids:data?.locationIds},'locationIds')})}catch(error){this.fail(error)}} }
