import { BadRequestException, Body, Controller, ForbiddenException, Get, Inject, NotFoundException, Param, Patch, Post, Query, Req, UnauthorizedException } from '@nestjs/common'
import { DatabaseService } from '../../database/database.service'
import { CHRONICLE_PARTICIPANT_REPOSITORY } from '../application/chronicle-participant.repository'
import type { ChronicleParticipantRepository } from '../application/chronicle-participant.repository'
import { parseChronicleIdParam, parseChronicleNarratorId } from './chronicle.dto'

type Kind='document'|'artifact'|'organization'
const prismaKind={document:'DOCUMENT',artifact:'ARTIFACT',organization:'ORGANIZATION'} as const
function kind(value:unknown):Kind{if(value==='document'||value==='artifact'||value==='organization')return value;throw new BadRequestException({code:'INVALID_CHRONICLE_RESOURCE_KIND'})}
function id(value:unknown){if(typeof value!=='string'||!/^[0-9a-f-]{36}$/i.test(value))throw new BadRequestException({code:'INVALID_CHRONICLE_RESOURCE_ID'});return value}
function payload(value:unknown,partial=false){if(typeof value!=='object'||value===null||Array.isArray(value))throw new BadRequestException({code:'INVALID_CHRONICLE_RESOURCE_REQUEST'});const v=value as Record<string,unknown>;const allowed=['kind','name','summary','narratorNotes','metadata'];if(Object.keys(v).some(k=>!allowed.includes(k)))throw new BadRequestException({code:'INVALID_CHRONICLE_RESOURCE_REQUEST'});const out:any={};if(!partial||v.kind!==undefined)out.kind=kind(v.kind);if(!partial||v.name!==undefined){if(typeof v.name!=='string'||v.name.trim().length<1||v.name.trim().length>160)throw new BadRequestException({code:'INVALID_CHRONICLE_RESOURCE_REQUEST'});out.name=v.name.trim()}for(const key of ['summary','narratorNotes'] as const)if(v[key]!==undefined){if(v[key]!==null&&typeof v[key]!=='string')throw new BadRequestException({code:'INVALID_CHRONICLE_RESOURCE_REQUEST'});out[key]=typeof v[key]==='string'&&v[key].trim()?v[key].trim():null}if(v.metadata!==undefined)out.metadata=v.metadata;return out}
function response(row:any){return{id:row.id,chronicleId:row.chronicleId,kind:String(row.kind).toLowerCase(),name:row.name,summary:row.summary,narratorNotes:row.narratorNotes,metadata:row.metadata,status:row.status,createdAt:row.createdAt.toISOString(),updatedAt:row.updatedAt.toISOString()}}
@Controller('chronicles/:chronicleId/resources')
export class ChronicleResourceController{
constructor(private readonly db:DatabaseService,@Inject(CHRONICLE_PARTICIPANT_REPOSITORY) private readonly participants:ChronicleParticipantRepository){}
private actor(req:any){try{return parseChronicleNarratorId(req.user?.id)}catch{throw new UnauthorizedException({code:'AUTHENTICATION_REQUIRED'})}}
private async access(req:any,c:unknown){const chronicleId=parseChronicleIdParam(c);const membership=await this.participants.findActiveMembership(chronicleId,this.actor(req));if(!membership||membership.role!=='narrator')throw new ForbiddenException({code:'CHRONICLE_RESOURCE_PERMISSION_DENIED'});return chronicleId}
@Get()async list(@Req()req:any,@Param('chronicleId')c:unknown,@Query()q:Record<string,unknown>){const chronicleId=await this.access(req,c);const limit=Math.min(Math.max(Number(q.limit)||25,1),100),offset=Math.max(Number(q.offset)||0,0);const where:any={chronicleId};if(q.kind!==undefined)where.kind=prismaKind[kind(q.kind)];if(q.status==='archived'||q.status==='active')where.status=q.status;const rows=await this.db.chronicleResource.findMany({where,orderBy:[{name:'asc'},{id:'asc'}],skip:offset,take:limit+1});return{items:rows.slice(0,limit).map(response),nextOffset:rows.length>limit?offset+limit:null}}
@Post()async create(@Req()req:any,@Param('chronicleId')c:unknown,@Body()body:unknown){const chronicleId=await this.access(req,c),data=payload(body);return response(await this.db.chronicleResource.create({data:{chronicleId,kind:prismaKind[data.kind as Kind],name:data.name,summary:data.summary??null,narratorNotes:data.narratorNotes??null,metadata:data.metadata}}))}
@Patch(':resourceId')async update(@Req()req:any,@Param('chronicleId')c:unknown,@Param('resourceId')r:unknown,@Body()body:unknown){const chronicleId=await this.access(req,c),resourceId=id(r),data=payload(body,true);if(data.kind)data.kind=prismaKind[data.kind as Kind];const result=await this.db.chronicleResource.updateMany({where:{id:resourceId,chronicleId},data});if(!result.count)throw new NotFoundException({code:'CHRONICLE_RESOURCE_NOT_FOUND'});return response(await this.db.chronicleResource.findUniqueOrThrow({where:{id:resourceId}}))}
@Patch(':resourceId/archive')async archive(@Req()req:any,@Param('chronicleId')c:unknown,@Param('resourceId')r:unknown){const chronicleId=await this.access(req,c),resourceId=id(r);const result=await this.db.chronicleResource.updateMany({where:{id:resourceId,chronicleId},data:{status:'archived'}});if(!result.count)throw new NotFoundException({code:'CHRONICLE_RESOURCE_NOT_FOUND'});return response(await this.db.chronicleResource.findUniqueOrThrow({where:{id:resourceId}}))}
}
