import { BadRequestException, Body, Controller, Delete, ForbiddenException, Get, Inject, NotFoundException, Param, Patch, Post, Put, Query, Req, StreamableFile, UnauthorizedException } from '@nestjs/common'
import { DatabaseService } from '../../database/database.service'
import { CHRONICLE_PARTICIPANT_REPOSITORY } from '../application/chronicle-participant.repository'
import type { ChronicleParticipantRepository } from '../application/chronicle-participant.repository'
import { parseChronicleIdParam, parseChronicleNarratorId } from './chronicle.dto'
import { createHash } from 'node:crypto'
const kinds=['npc','location','organization','artifact','document'] as const
const id=(v:unknown)=>{if(typeof v!=='string'||!/^[0-9a-f-]{36}$/i.test(v))throw new BadRequestException({code:'INVALID_LIBRARY_RESOURCE_ID'});return v}
const owner=(r:any)=>{try{return parseChronicleNarratorId(r.user?.id)}catch{throw new UnauthorizedException({code:'AUTHENTICATION_REQUIRED'})}}
const out=(r:any)=>({id:r.id,kind:r.kind,name:r.name,summary:r.summary,narratorNotes:r.narratorNotes,metadata:r.metadata,status:r.status,legacyType:r.legacyType,createdAt:r.createdAt.toISOString(),updatedAt:r.updatedAt.toISOString()})
function body(v:unknown,partial=false){if(!v||typeof v!=='object'||Array.isArray(v))throw new BadRequestException({code:'INVALID_LIBRARY_RESOURCE_REQUEST'});const x=v as any,o:any={};if(!partial||x.kind!==undefined){if(!kinds.includes(x.kind))throw new BadRequestException({code:'INVALID_LIBRARY_RESOURCE_KIND'});o.kind=x.kind}if(!partial||x.name!==undefined){if(typeof x.name!=='string'||!x.name.trim()||x.name.trim().length>160)throw new BadRequestException({code:'INVALID_LIBRARY_RESOURCE_NAME'});o.name=x.name.trim()}for(const k of ['summary','narratorNotes'])if(x[k]!==undefined)o[k]=typeof x[k]==='string'&&x[k].trim()?x[k].trim():null;if(x.metadata!==undefined)o.metadata=x.metadata;return o}
@Controller('library/resources')
export class LibraryResourceController {
 constructor(private readonly db:DatabaseService,@Inject(CHRONICLE_PARTICIPANT_REPOSITORY)private readonly participants:ChronicleParticipantRepository){}
 @Get()async list(@Req()r:any,@Query()q:any){const status=q.status===undefined?'active':q.status;if(status!=='active'&&status!=='archived')throw new BadRequestException({code:'INVALID_LIBRARY_RESOURCE_STATUS'});const where:any={ownerId:owner(r),status};if(q.kind!==undefined){if(!kinds.includes(q.kind))throw new BadRequestException({code:'INVALID_LIBRARY_RESOURCE_KIND'});where.kind=q.kind};return{items:(await this.db.libraryResource.findMany({where,orderBy:{name:'asc'},take:100})).map(out)}}
 @Post()async create(@Req()r:any,@Body()b:unknown){return out(await this.db.libraryResource.create({data:{ownerId:owner(r),...body(b)}}))}
 @Patch(':resourceId')async update(@Req()r:any,@Param('resourceId')raw:unknown,@Body()b:unknown){const resourceId=id(raw),result=await this.db.libraryResource.updateMany({where:{id:resourceId,ownerId:owner(r)},data:body(b,true)});if(!result.count)throw new NotFoundException({code:'LIBRARY_RESOURCE_NOT_FOUND'});return out(await this.db.libraryResource.findUniqueOrThrow({where:{id:resourceId}}))}
 @Post(':resourceId/attach')async attach(@Req()r:any,@Param('resourceId')raw:unknown,@Body()b:any){const ownerId=owner(r),resourceId=id(raw),chronicleId=parseChronicleIdParam(b?.chronicleId),m=await this.participants.findActiveMembership(chronicleId,ownerId);if(!m||m.role!=='narrator')throw new ForbiddenException({code:'LIBRARY_RESOURCE_ATTACH_DENIED'});if(!await this.db.libraryResource.findFirst({where:{id:resourceId,ownerId}}))throw new NotFoundException({code:'LIBRARY_RESOURCE_NOT_FOUND'});const visibility=b?.visibility==='chronicle_participants'?'chronicle_participants':'narrator_only';const row=await this.db.chronicleResourceBinding.upsert({where:{chronicleId_resourceId:{chronicleId,resourceId}},create:{chronicleId,resourceId,visibility},update:{status:'attached',visibility}});return{id:row.id,chronicleId:row.chronicleId,resourceId:row.resourceId,visibility:row.visibility}}

 @Post(':resourceId/archive')async archive(@Req()r:any,@Param('resourceId')raw:unknown){const resourceId=id(raw),ownerId=owner(r);const result=await this.db.libraryResource.updateMany({where:{id:resourceId,ownerId,status:'active'},data:{status:'archived'}});if(!result.count&&!await this.db.libraryResource.findFirst({where:{id:resourceId,ownerId}}))throw new NotFoundException({code:'LIBRARY_RESOURCE_NOT_FOUND'});return{archived:true}}
 @Post(':resourceId/restore')async restore(@Req()r:any,@Param('resourceId')raw:unknown){const resourceId=id(raw),ownerId=owner(r);const result=await this.db.libraryResource.updateMany({where:{id:resourceId,ownerId,status:'archived'},data:{status:'active'}});if(!result.count&&!await this.db.libraryResource.findFirst({where:{id:resourceId,ownerId}}))throw new NotFoundException({code:'LIBRARY_RESOURCE_NOT_FOUND'});return{restored:true}}
 @Delete(':resourceId')async remove(@Req()r:any,@Param('resourceId')raw:unknown){const resourceId=id(raw),ownerId=owner(r);await this.db.chronicleResourceBinding.deleteMany({where:{resourceId}});const result=await this.db.libraryResource.deleteMany({where:{id:resourceId,ownerId,status:'archived'}});if(!result.count)throw new NotFoundException({code:'LIBRARY_RESOURCE_ARCHIVED_NOT_FOUND'});return{deleted:true}}

 private async resourceImage(req:any,raw:unknown){const resource=await this.db.libraryResource.findFirst({where:{id:id(raw),ownerId:owner(req)}});if(!resource)throw new NotFoundException({code:'LIBRARY_RESOURCE_NOT_FOUND'});const assetType=resource.kind==='npc'?'NPC':resource.kind==='location'?'LOCATION':'RESOURCE';return{resource,assetType}}
 @Get(':resourceId/image')async image(@Req()req:any,@Param('resourceId')raw:unknown){const x=await this.resourceImage(req,raw),image=await this.db.chronicleAssetImage.findUnique({where:{assetType_entityId:{assetType:x.assetType,entityId:x.resource.id}}});if(!image)throw new NotFoundException({code:'LIBRARY_RESOURCE_IMAGE_NOT_FOUND'});return new StreamableFile(Buffer.from(image.data),{type:image.mimeType,length:image.byteSize,disposition:'inline'})}
 @Put(':resourceId/image')async saveImage(@Req()req:any,@Param('resourceId')raw:unknown){const x=await this.resourceImage(req,raw),parts:Buffer[]=[];let size=0;for await(const part of req){const chunk=Buffer.isBuffer(part)?part:Buffer.from(part);size+=chunk.length;if(size>2097152)throw new BadRequestException({code:'LIBRARY_RESOURCE_IMAGE_TOO_LARGE'});parts.push(chunk)}const data=Buffer.concat(parts),mime=req.headers['content-type']?.split(';')[0];if(!data.length||!['image/jpeg','image/png','image/webp'].includes(mime))throw new BadRequestException({code:'LIBRARY_RESOURCE_IMAGE_INVALID'});const image=await this.db.chronicleAssetImage.upsert({where:{assetType_entityId:{assetType:x.assetType,entityId:x.resource.id}},create:{assetType:x.assetType,entityId:x.resource.id,mimeType:mime,byteSize:data.length,sha256:createHash('sha256').update(data).digest('hex'),data},update:{mimeType:mime,byteSize:data.length,sha256:createHash('sha256').update(data).digest('hex'),data,updatedAt:new Date()}});return{mimeType:image.mimeType,byteSize:image.byteSize}}
 @Delete(':resourceId/image')async removeImage(@Req()req:any,@Param('resourceId')raw:unknown){const x=await this.resourceImage(req,raw);await this.db.chronicleAssetImage.deleteMany({where:{assetType:x.assetType,entityId:x.resource.id}});return{removed:true}}

}
